---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-service-secret
  namespace: default
spec:
  encryptedData:
    JWT_SECRET: AgBlARYaDMc71yyvLECspUr+pfH/+fQyOTcsf6SHKmwniLNFnxENp0HU3kxsYLSUvCHZq8DCb8ugwmqJQs03kJ9y5zBIhYjnzfCY9CL/iGTduPfxavWK15DuMWzPsXvqMdo6dDj7qQBGEGFjJRufJazBhTtD+F6gZ7A82kIXrM9KdGBfZ+dGrIzvFnTGIJJJz+wyhkYdItEzodl4ZQblJTe7k7AsB7eHPIE4IZiSVPQX/nhSh9EMuRwj7NBzq8fh5tlgmlh06pYZMBCYB7fGh0AMrP8Kvph2HIW0ZFXreC+PaGJC+2FJ3lRi6ZmpDExv3Jz7Io10Tq9zPcb5JVe3sSuFedVNCj3jcoQu7pIy6WFmB2A0XveQR27BKwsR7by4neV41Po5xzl7NA13RFD4j7EUjJePr69Ht7JcncVonKO2DTTQFQEB2yvCy3wqt4iPBl87uRyQCugU75r6R0pG/mPJ4oGIlWJfCAqXwgEtOyGzJfitMzoqI8rnMYeLRPlrH5WyoxGZHVR5m8VkAElghEiq3KrtPgzzBfngkKvciUDMNNnczwon8kpLy3kyF7QT+33DIAv4Bxd9YO+vZuIp72WQTX+ym3OLWXM55LJt/fDOcH9pU371N/WGOpbZ1fANy37cltaTCtZHrcMiOivgivatvod7G++RMEb11CUIUCa7uLITQMD7PDcogQkDfDOLPTQrXQaavNovXf+iBw4UbwWmCNKij/TVz46W/9O6ct3l/LPlPH2MNucYiDEUEE1NtEJudpQwfcxcwngbwFZgikvBGj4HR3dUrJ1z1VkGDn0O476eR2fQQgTmrHcq5NV7Qcpk5YMY0JngCKRR7/NjjWATkNUjbQ==
  template:
    metadata:
      creationTimestamp: null
      name: auth-service-secret
      namespace: default
    type: Opaque
