CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    display_name VARCHAR(50) NOT NULL,
    bcrypt_password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);